# Generated by Django 4.2.7 on 2023-12-07 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_directmessage_receiver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directmessage',
            name='chat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='users.chatlist'),
            preserve_default=False,
        ),
    ]
