# Generated by Django 4.2.7 on 2023-12-07 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_directmessage_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='directmessage',
            name='sender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='users.profile'),
            preserve_default=False,
        ),
    ]
