# Generated by Django 4.2.7 on 2024-01-03 18:59

from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_directmessages_delete_directmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('answer', models.TextField(blank=True, null=True)),
                ('state', django_fsm.FSMField(choices=[(1, 'created'), (2, 'pending'), (3, 'answered'), (4, 'closed')], default=1, max_length=50, protected=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='users.profile')),
            ],
            options={
                'verbose_name_plural': 'چت ها',
            },
        ),
    ]
