# Generated by Django 4.2.7 on 2024-01-03 20:44

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_ticket'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name_plural': 'تیکت ها'},
        ),
        migrations.AlterField(
            model_name='ticket',
            name='state',
            field=django_fsm.FSMField(choices=[('CR', 'created'), ('PE', 'pending'), ('AN', 'answered'), ('CL', 'closed')], default='CR', max_length=50, protected=True),
        ),
    ]
